version: "3"
services:
  # React app container
  react-app:
    build:
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - ./src:/app/src # Optional: Map your source code for live development

# You can add more services like a database or API if needed
